[project]
name = "speedreading-app"
org = "dev.disobey"

[core]
crate = "readstr_core"
bindings = "uniffi"

[ios]
bundle_id = "dev.disobey.speedreading"

[android]
app_id = "dev.disobey.readstr"

[desktop]
targets = ["iced"]

[desktop.iced]
package = "readstr_desktop"
