//! Update types: AppUpdate crosses FFI, CoreMsg and InternalEvent are internal only.

use crate::state::{AppState, WordDisplay};

/// Sent from actor to platform reconcilers via the update channel.
/// AppUpdate::FullState on any state change except active playback tick.
/// AppUpdate::PlaybackTick during active playback to avoid cloning full AppState.
#[derive(uniffi::Enum, Clone, Debug)]
pub enum AppUpdate {
    FullState(AppState),
    PlaybackTick {
        display: WordDisplay,
        progress_percent: f32,
        current_word_index: u64,
    },
}

/// Actor message envelope — NOT exported via UniFFI.
/// Routes both external actions and internal events through a single channel.
pub enum CoreMsg {
    Action(crate::actions::AppAction),
    Internal(InternalEvent),
}

/// Internal events generated by async tasks running on the actor's tokio runtime.
/// NOT exported via UniFFI — never crosses the FFI boundary.
pub enum InternalEvent {
    ParseComplete {
        words: Vec<String>,
        file_hash: Option<String>,  // None for LoadText (paste); Some(64-char hex) for file opens
        file_name: Option<String>,  // None for LoadText; Some("filename.epub") for file opens
        file_path: Option<String>,  // None for LoadText; Some("/full/path") for file opens
    },
    ParseError { message: String },
    WordAdvance,
}
